language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install flake8
  - pip install coveralls
script:
  - coverage run --source=vladiate setup.py test
  - flake8 .
after_success:
  - coveralls
